### ISSUE TITLE
SauceConnect failing?

### ISSUE THREAD

**Issue by nwwells** [webdriverio/wdio-sauce-service#23]
```
Opening local tunnel using Sauce Connect
Starting sc with args: -u XXXXXXXX -k XXXXXXXX --verbose -vv -P 4445 --log-stats 5 --readyfile /var/folders/8m/y7txsryn7ms7sfvtz11tjfyw0000gn/T/sc-launcher-readyfile
A service failed in the 'onPrepare' hook
Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at connect (/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:494:11)
    at /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:599:12
    at tryRun (/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/try_run.js:4:3)
    at run (/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:594:3)
    at /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:623:14
    at nextTask (/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/async/dist/async.js:5210:14)
    at /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/async/dist/async.js:5204:13
```

**Comment by christian-bromann** [comment]
@nwwells I guess this is due to the missing SC binary as reported in your last issue. This is nothing that can be fixed within this project. I had no issues using SC with default params.
